[tool.poetry]
name = "child-lab-framework"
version = "0.1.0"
description = "UJ ChildLab Computer Vision project"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
