[tool.poetry]
name = "child-lab-framework"
version = "0.1.0"
description = "UJ ChildLab Computer Vision project"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{ include = "child_lab_framework" }]

[tool.poetry.dependencies]
python = "^3.12"
docker = "^7.1.0"
websockets = "^12.0"
opencv-python = "^4.10.0.84"
ultralytics = "^8.2.72"
mediapipe = "^0.10.14"
colorama = "^0.4.6"
onnxruntime = "^1.18.1"
numba = "^0.60.0"

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.26.1"
black = "^24.4.2"
pylint = "^3.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
format = "black ."
build_whl = "poetry build"
install_whl = "pip install --force-reinstall dist/*.whl"
prepare = ["build_whl", "install_whl"]

[tool.poe.tasks.lint]
shell = "find child_lab_framework -name '*.py' | xargs pylint"
