[tool.poetry]
name = "child-lab-framework"
version = "0.1.0"
description = "UJ ChildLab Computer Vision project"
authors = [
    "Jan Smółka <jp.smolka@gmail.com>",
    "Igor Urbanik <igorurbanik23@gmail.com>",
]
readme = "README.md"
packages = [{ include = "child_lab_framework" }]

[tool.poetry.dependencies]
python = "^3.12"
opencv-python = "^4.10.0.84"
ultralytics = "^8.2.72"
colorama = "^0.4.6"
networkx = "^3.3"
scipy = "^1.14.1"
pandas = "^2.2.2"
mini-face = "^0.1.3"
depth-pro = { git = "https://github.com/child-lab-uj/depth-pro.git" }
click = "^8.1.7"
more-itertools = "^10.5.0"
kornia = "^0.7.4"
types-tqdm = "^4.67.0.20241221"
types-networkx = "^3.4.2.20241227"

[tool.poetry.group.dev.dependencies]
poethepoet = "^0.26.1"
icecream = "^2.1.3"
ruff = "^0.6.8"
mypy = "^1.11.2"
spin = "^0.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
exclude = [".venv", "child_lab_framework/experiments"]
line-length = 90

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

[tool.mypy]
packages = ["child_lab_framework"]
exclude = ["venv"]
incremental = true
strict = true
allow_untyped_globals = false
disallow_any_expr = false
disallow_any_unimported = true
disallow_any_decorated = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_defs = true
disallow_untyped_calls = true
disallow_incomplete_defs = true
implicit_optional = false
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
follow_untyped_imports = true

[tool.mypy-networkx]
ignore_missing_imports = true


[tool.poe.tasks]
format = "ruff format"
lint = "ruff check"
check = "mypy --config-file pyproject.toml"
build_whl = "poetry build"
install_whl = "pip install --force-reinstall dist/*.whl"
prepare = ["build_whl", "install_whl"]

[tool.spin.commands]
"Development" = ["spin/development.py:workspace", "spin/development.py:video"]
