[project]
name = "child-lab-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jan Smółka", email = "jp.smolka@gmail.com" }
]
requires-python = ">=3.12.7"
dependencies = [
    "beartype>=0.20.2",
    "jaxtyping>=0.3.2",
    "plum-dispatch>=2.5.7",
    "tensordict>=0.8.2",
    "torch>=2.7.0",
    "vpc",
]

[tool.uv.sources]
vpc = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
