[project]
name = "vpc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jan Smółka", email = "jp.smolka@gmail.com" }
]
requires-python = ">=3.12.7"
dependencies = [
    "jaxtyping>=0.3.2",
    "kornia>=0.8.0",
    "mini-face>=0.1.3",
    "more-itertools>=10.7.0",
    "opencv-python>=4.11.0.86",
    "torch>=2.7.0",
    "torchvision>=0.22.0",
    "ultralytics>=8.3.121",
    "video-io",
]

[tool.uv.sources]
video-io = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
