[project]
name = "child-lab-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "click>=8.1.8",
    "pyserde>=0.23.0",
    "torch>=2.6.0",
    "tqdm>=4.67.1",
    "viser>=0.2.23",
    "child-lab-data",
    "child-lab-visualization",
    "child-lab-procedures",
    "depth-estimation",
    "marker-detection",
    "transformation-buffer",
    "video-io",
    "vpc",
    "colorlog>=6.9.0",
    "types-tqdm>=4.67.0.20250516",
    "opencv-python>=4.11.0.86",
]

[tool.uv.sources]
child-lab-data = { workspace = true }
child-lab-procedures = { workspace = true }
child-lab-visualization = { workspace = true }
depth-estimation = { workspace = true }
marker-detection = { workspace = true }
transformation-buffer = { workspace = true }
video-io = { workspace = true }
vpc = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
child-lab = "child_lab_cli:child_lab"
