[project]
name = "video-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jan Smółka", email = "jp.smolka@gmail.com" }
]
requires-python = ">=3.12.7"
dependencies = [
    "annotated-types>=0.7.0",
    "attrs>=25.1.0",
    "jaxtyping>=0.2.37",
    "more-itertools>=10.6.0",
    "opencv-python>=4.11.0.86",
    "torch>=2.5.1",
    "torchcodec>=0.2.0",
    "torchvision>=0.21.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "icecream>=2.1.4",
    "pytest-benchmark[histogram]>=5.1.0",
]
