name: CI

on: pull_request

jobs:
  build:
    name: Build and check the project
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"  # Invalidate the cache if the lockfile has changed

      # According to the docs, this solution can be faster than `uv python install`
      # because of the external caching performed by GitHub.
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check format
        run: uv run ruff format --check

      - name: Check lints
        run: uv run ruff check

      - name: Check types
        run: uv run mypy . --config-file pyproject.toml

  typos:
    name: Check typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: typos-action
        uses: crate-ci/typos@v1.24.5
