[project]
name = "child-lab-procedures"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jan Smółka", email = "jp.smolka@gmail.com" }
]
requires-python = ">=3.12.7"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
